# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics(api_token: "api_token")

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    #gradle(task: "clean assembleRelease")
          path = "../app/build.gradle"
          re = /versionCode\s+(\d+)/
          s = File.read(path)
          versionCode = s[re, 1].to_i
          #s[re, 1] = (versionCode + 1).to_s
          #f = File.new(path, 'w')
          #f.write(s)
          #f.close
    gradle(
      task: "assemble",
      build_type: "Release",
      print_command: false,
      properties: {
        versionCode" => 22,
        "versionName" => "1.0.8",
        "android.injected.signing.store.file" => "Untitled",
        "android.injected.signing.store.password" => "cicdtest",
        "android.injected.signing.key.alias" => "cicdtest",
        "android.injected.signing.key.password" => "cicdtest",

      }
    )
    supply(
             apk_paths: "../build/app/outputs/apk/release/app-release.apk",
             skip_upload_changelogs: true
        )
    upload_to_play_store

   end

   desc ""
   lane :distribute do
    gradle(
        task: 'assemble',
        build_type: 'Release'
    )
        firebase_app_distribution(
            app: "app.cpplayer.com.flutterappcicd",
            firebase_cli_token: "1//0g2_7YlUBmh5mCgYIARAAGBASNwF-L9Irh-VgRc5fQF9Lv_qYfEfPMtThbX7z2BKgZY4kyvIl5IbCYxl4A2zbE9FxNDH7b9HnZm0",
            testers: "",
            release_notes: "",
            firebase_cli_path: "/usr/local/bin/firebase",
            apk_path: "../build/app/outputs/apk/release/app-release.apk"
        )
    end

    desc "Deploy a new beta build to Google Play"
    lane :flutterdeploy do
      path = '../app/build.gradle'
          re = /versionCode\s+(\d+)/
          s = File.read(path)
          versionCode = s[re, 1].to_i
          s[re, 1] = (versionCode + 1).to_s
          f = File.new(path, 'w')
          f.write(s)
          f.close
   end
end
